# Generated by Django 5.0.6 on 2024-06-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='immediate_contact',
            field=models.CharField(default=8462, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
