# Generated by Django 5.0.6 on 2024-06-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='country',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='phone_number',
            new_name='electronics',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='class',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='class',
            name='email',
        ),
        migrations.RemoveField(
            model_name='class',
            name='immediate_contact',
        ),
        migrations.RemoveField(
            model_name='class',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='pic',
        ),
        migrations.AddField(
            model_name='class',
            name='building_material',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.SmallIntegerField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='class_id',
            field=models.SmallIntegerField(default=True, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='class_temperature',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='class',
            name='sitting_arrangement',
            field=models.FileField(default=True, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='size',
            field=models.CharField(default=True, max_length=12),
            preserve_default=False,
        ),
    ]
